# Generated by Django 4.1.1 on 2022-10-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_date_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='important',
            new_name='Low_importance',
        ),
        migrations.AddField(
            model_name='task',
            name='high_importance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='medium_importance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
